-- travel-recorder 스키마 (PostgreSQL)
--
-- 엔티티(com.yong.travel.*.domain)로부터 Hibernate 가 생성하는 DDL 을 기준으로 작성했다.
-- 컬럼 타입/이름을 바꾸면 `ddl-auto: validate` 가 실패하므로 엔티티와 함께 수정해야 한다.
--
-- - 재실행해도 안전하도록 모든 DDL 은 IF NOT EXISTS 를 사용하고,
--   외래키는 ALTER TABLE 대신 CREATE TABLE 안에 인라인으로 선언한다.
-- - 따라서 테이블은 참조 순서(users → tags → places → 나머지)대로 정의한다.
-- - H2 는 MODE=PostgreSQL 로 기동하므로 local 프로파일에서도 이 스크립트를 그대로 쓴다.

-- 사용자 (네이버 OAuth2 로그인)
CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider          VARCHAR(255)                NOT NULL,
    provider_id       VARCHAR(255)                NOT NULL,
    email             VARCHAR(255)                NOT NULL,
    name              VARCHAR(255)                NOT NULL,
    profile_image_url VARCHAR(255),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_provider UNIQUE (provider, provider_id)
);

-- 태그 (여행지에 다중 부착되는 자유 키워드)
CREATE TABLE IF NOT EXISTS tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tags_name UNIQUE (name)
);

-- 여행지
CREATE TABLE IF NOT EXISTS places
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id      BIGINT                      NOT NULL,
    name          VARCHAR(255)                NOT NULL,
    category      VARCHAR(255)                NOT NULL,
    address       VARCHAR(255)                NOT NULL,
    road_address  VARCHAR(255),
    external_link VARCHAR(255),
    latitude      DOUBLE PRECISION            NOT NULL,
    longitude     DOUBLE PRECISION            NOT NULL,
    memo          VARCHAR(1000),
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_places_category CHECK (category IN ('SIGHT', 'SHOPPING', 'FOOD')),
    CONSTRAINT fk_places_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

-- 여행지 ↔ 태그 조인 테이블
CREATE TABLE IF NOT EXISTS place_tags
(
    place_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL,
    PRIMARY KEY (place_id, tag_id),
    CONSTRAINT fk_place_tags_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_place_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

-- 평점 (사용자당 여행지 1건)
CREATE TABLE IF NOT EXISTS ratings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    place_id   BIGINT                      NOT NULL,
    user_id    BIGINT                      NOT NULL,
    score      INTEGER                     NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_ratings_place_user UNIQUE (place_id, user_id),
    CONSTRAINT fk_ratings_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_ratings_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 댓글
CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    place_id   BIGINT                      NOT NULL,
    author_id  BIGINT                      NOT NULL,
    content    VARCHAR(1000)               NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_comments_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- 사진 (파일 본체는 app.storage 설정 위치에 저장하고 여기에는 메타데이터만 둔다)
CREATE TABLE IF NOT EXISTS photos
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    place_id           BIGINT                      NOT NULL,
    uploader_id        BIGINT                      NOT NULL,
    storage_key        VARCHAR(255)                NOT NULL,
    original_file_name VARCHAR(255)                NOT NULL,
    content_type       VARCHAR(255)                NOT NULL,
    file_size_bytes    BIGINT                      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_photos_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_photos_uploader FOREIGN KEY (uploader_id) REFERENCES users (id)
);

-- 인덱스
-- PostgreSQL 은 외래키에 인덱스를 자동 생성하지 않으므로, 조회·삭제 시 사용되는 FK 컬럼에 직접 만든다.
CREATE INDEX IF NOT EXISTS idx_places_owner ON places (owner_id);
CREATE INDEX IF NOT EXISTS idx_places_category ON places (category);
CREATE INDEX IF NOT EXISTS idx_places_created_at ON places (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_place_tags_tag ON place_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_ratings_place ON ratings (place_id);
CREATE INDEX IF NOT EXISTS idx_comments_place ON comments (place_id);
CREATE INDEX IF NOT EXISTS idx_photos_place ON photos (place_id);
CREATE INDEX IF NOT EXISTS idx_photos_uploader ON photos (uploader_id);
