-- travel-recorder 스키마 (PostgreSQL)
--
-- 엔티티(com.yong.travel.*.domain)로부터 Hibernate 가 생성하는 DDL 을 기준으로 작성했다.
-- 컬럼 타입/이름을 바꾸면 `ddl-auto: validate` 가 실패하므로 엔티티와 함께 수정해야 한다.
--
-- - 재실행해도 안전하도록 모든 DDL 은 IF NOT EXISTS 를 사용하고,
--   외래키는 ALTER TABLE 대신 CREATE TABLE 안에 인라인으로 선언한다.
-- - 따라서 테이블은 참조 순서(users → tags → visit_records → 나머지)대로 정의한다.
-- - H2 는 MODE=PostgreSQL 로 기동하므로 local 프로파일에서도 이 스크립트를 그대로 쓴다.
--
-- 저장 단위는 visit_records 하나뿐이다. 장소 마스터 데이터는 외부(네이버 지역 검색)에서 조회할 뿐
-- 자체 테이블로 두지 않으며, 장소명·주소·좌표·원본 링크는 기록에 스냅샷으로 복사된다.
--
-- visit_records 는 soft delete 를 쓴다. deleted_at 이 NULL 인 행만 살아 있는 행이며,
-- 엔티티의 @SQLRestriction("deleted_at is null") 이 조회에서 자동으로 걸러 낸다.
-- 별도의 is_deleted / delete_yn 플래그는 두지 않는다 (deleted_at 과 어긋날 여지만 생긴다).
-- 반대로 그룹·멤버·초대·공유 관계는 물리 삭제한다. 탈퇴와 공유 해제는 즉시 조회 권한을 없애야 하는
-- 동작이라, 남아 있는 행이 권한 판정에 끼어들 여지를 만들지 않는다.

-- 사용자 (네이버 OAuth2 로그인)
-- email 은 초대 대상을 지정하는 유일한 열쇠라 계정마다 하나여야 한다 (유니크).
-- 대신 NULL 을 허용한다 — 이메일 제공 동의를 받지 못한 계정을 빈 문자열로 채우면
-- 그런 계정이 둘째로 생기는 순간 유니크 제약에 걸려 로그인 자체가 실패한다. NULL 끼리는 충돌하지 않는다.
CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider          VARCHAR(255)                NOT NULL,
    provider_id       VARCHAR(255)                NOT NULL,
    email             VARCHAR(255),
    name              VARCHAR(255)                NOT NULL,
    profile_image_url VARCHAR(255),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_provider UNIQUE (provider, provider_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- 태그 (기록에 다중 부착되는 자유 키워드)
CREATE TABLE IF NOT EXISTS tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tags_name UNIQUE (name)
);

-- 공유 그룹 (조회 전용 대상 목록)
-- group 은 SQL 예약어라 테이블명만 share_group 으로 둔다.
CREATE TABLE IF NOT EXISTS share_group
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id   BIGINT                      NOT NULL,
    name       VARCHAR(30)                 NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_share_group_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

-- 그룹 멤버 (소유자도 멤버 행을 가진다)
-- 정원(5명) 제한은 애플리케이션에서 검증한다. 행 수를 세는 조건이라 CHECK 로 표현할 수 없다.
CREATE TABLE IF NOT EXISTS group_member
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id  BIGINT                      NOT NULL,
    user_id   BIGINT                      NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_group_member UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_member_group FOREIGN KEY (group_id) REFERENCES share_group (id),
    CONSTRAINT fk_group_member_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 그룹 초대 (소유자가 특정 가입자 앞으로 보내는 요청. 받은 사람의 계정에 쌓인다)
-- 토큰·만료 컬럼을 두지 않는다. 초대가 서비스 밖으로 나가지 않아 추측할 대상도 수명도 없다.
-- 상태 컬럼도 두지 않는다. 수락·거절·철회가 모두 행 삭제로 끝난다.
-- 정원(5명) 판정은 수락 시점에만 하므로 대기 초대 건수는 제약하지 않는다.
CREATE TABLE IF NOT EXISTS group_invite
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id   BIGINT                      NOT NULL,
    invitee_id BIGINT                      NOT NULL,
    invited_by BIGINT                      NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_group_invite UNIQUE (group_id, invitee_id),
    CONSTRAINT fk_group_invite_group FOREIGN KEY (group_id) REFERENCES share_group (id),
    CONSTRAINT fk_group_invite_invitee FOREIGN KEY (invitee_id) REFERENCES users (id),
    CONSTRAINT fk_group_invite_inviter FOREIGN KEY (invited_by) REFERENCES users (id)
);

-- 방문 기록 (개인 소유, 서비스의 유일한 저장 단위)
-- rating 은 0.5 ~ 5.0 을 0.5 단위로만 받는다. 허용 값을 CHECK 로 나열해 두면
-- 애플리케이션 검증이 우회되더라도 DB 가 마지막으로 막아 준다.
-- visibility 기본값은 PRIVATE 이다. 값을 빠뜨린 INSERT 가 공개로 저장되는 쪽이
-- 훨씬 위험하므로 DB 기본값도 같은 방향으로 맞춰 둔다.
CREATE TABLE IF NOT EXISTS visit_records
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id     BIGINT                      NOT NULL,
    name          VARCHAR(255)                NOT NULL,
    category      VARCHAR(255)                NOT NULL,
    address       VARCHAR(255)                NOT NULL,
    road_address  VARCHAR(255),
    external_link VARCHAR(255),
    latitude      DOUBLE PRECISION            NOT NULL,
    longitude     DOUBLE PRECISION            NOT NULL,
    rating        DOUBLE PRECISION            NOT NULL,
    memo          VARCHAR(1000),
    visibility    VARCHAR(255)                NOT NULL DEFAULT 'PRIVATE',
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT ck_visit_records_category CHECK (category IN ('SIGHT', 'SHOPPING', 'FOOD')),
    CONSTRAINT ck_visit_records_visibility CHECK (visibility IN ('PRIVATE', 'GROUP', 'PUBLIC')),
    CONSTRAINT ck_visit_records_rating CHECK (rating IN (0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5)),
    CONSTRAINT fk_visit_records_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- 기록 ↔ 태그 조인 테이블
CREATE TABLE IF NOT EXISTS visit_record_tags
(
    record_id BIGINT NOT NULL,
    tag_id    BIGINT NOT NULL,
    PRIMARY KEY (record_id, tag_id),
    CONSTRAINT fk_visit_record_tags_record FOREIGN KEY (record_id) REFERENCES visit_records (id),
    CONSTRAINT fk_visit_record_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

-- 기록 ↔ 그룹 공유 관계 (visibility = GROUP 일 때만 사용)
CREATE TABLE IF NOT EXISTS visit_record_share
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id BIGINT NOT NULL,
    group_id  BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_visit_record_share UNIQUE (record_id, group_id),
    CONSTRAINT fk_visit_record_share_record FOREIGN KEY (record_id) REFERENCES visit_records (id),
    CONSTRAINT fk_visit_record_share_group FOREIGN KEY (group_id) REFERENCES share_group (id)
);

-- 사진 (파일 본체는 app.storage 설정 위치에 저장하고 여기에는 메타데이터만 둔다)
-- 업로더 컬럼은 두지 않는다. 올릴 수 있는 사람이 기록 작성자뿐이라 visit_records.author_id 와 같은 값이다.
CREATE TABLE IF NOT EXISTS photos
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id          BIGINT                      NOT NULL,
    storage_key        VARCHAR(255)                NOT NULL,
    original_file_name VARCHAR(255)                NOT NULL,
    content_type       VARCHAR(255)                NOT NULL,
    file_size_bytes    BIGINT                      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_photos_record FOREIGN KEY (record_id) REFERENCES visit_records (id)
);

-- 인덱스
-- PostgreSQL 은 외래키에 인덱스를 자동 생성하지 않으므로, 조회·삭제 시 사용되는 FK 컬럼에 직접 만든다.
-- soft delete 대상 테이블은 조회 시 deleted_at 조건이 항상 붙으므로 복합 인덱스로 만든다.
-- (PostgreSQL 의 부분 인덱스가 더 좋지만 H2 가 지원하지 않아 local 과 스크립트를 공유하지 못한다.)
CREATE INDEX IF NOT EXISTS idx_visit_records_author ON visit_records (author_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_visit_records_category ON visit_records (category);
CREATE INDEX IF NOT EXISTS idx_visit_records_created_at ON visit_records (created_at DESC);
-- 둘러보기 탭(공개 기록 목록)이 가장 넓은 범위를 훑으므로 공개 범위에도 인덱스를 둔다.
CREATE INDEX IF NOT EXISTS idx_visit_records_visibility ON visit_records (visibility, deleted_at);
CREATE INDEX IF NOT EXISTS idx_visit_record_tags_tag ON visit_record_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_visit_record_share_group ON visit_record_share (group_id);
CREATE INDEX IF NOT EXISTS idx_group_member_user ON group_member (user_id);
-- 받은 초대 목록 조회 경로. (group_id 는 uk_group_invite 의 선두 컬럼이라 따로 만들지 않는다.)
CREATE INDEX IF NOT EXISTS idx_group_invite_invitee ON group_invite (invitee_id);
CREATE INDEX IF NOT EXISTS idx_share_group_owner ON share_group (owner_id);
CREATE INDEX IF NOT EXISTS idx_photos_record ON photos (record_id);
