-- travel-recorder 스키마 (PostgreSQL)
--
-- 엔티티(com.yong.travel.*.persistence)로부터 Hibernate 가 생성하는 DDL 을 기준으로 작성했다.
-- 컬럼 타입/이름을 바꾸면 `ddl-auto: validate` 가 실패하므로 엔티티와 함께 수정해야 한다.
--
-- - 재실행해도 안전하도록 모든 DDL 은 IF NOT EXISTS 를 사용하고,
--   외래키는 ALTER TABLE 대신 CREATE TABLE 안에 인라인으로 선언한다.
-- - 따라서 테이블은 참조 순서(users → tags → trips → trip_records → 나머지)대로 정의한다.
-- - H2 는 MODE=PostgreSQL 로 기동하므로 local 프로파일에서도 이 스크립트를 그대로 쓴다.
--
-- 저장 단위는 trips 와 그 하위 trip_records 다. 공개 범위는 trips 에만 있고 기록은 소속 여행을
-- 따른다. 장소 마스터 데이터는 외부(네이버 지역 검색)에서 조회할 뿐 자체 테이블로 두지 않으며,
-- 장소명·주소·좌표·원본 링크는 기록에 스냅샷으로 복사된다.
--
-- trips 와 trip_records 는 soft delete 를 쓴다. deleted_at 이 NULL 인 행만 살아 있는 행이며,
-- 엔티티의 @SQLRestriction("deleted_at is null") 이 조회에서 자동으로 걸러 낸다.
-- 별도의 is_deleted / delete_yn 플래그는 두지 않는다 (deleted_at 과 어긋날 여지만 생긴다).
-- 반대로 그룹·멤버·초대·공유 관계는 물리 삭제한다. 탈퇴와 공유 해제는 즉시 조회 권한을 없애야 하는
-- 동작이라, 남아 있는 행이 권한 판정에 끼어들 여지를 만들지 않는다.

-- 사용자 (로그인 계정)
-- provider 는 로그인 수단 식별자다 — 네이버 OAuth 는 'naver', 임시 인메모리 로그인은 'local'
-- 이며, provider + provider_id 조합으로 동일인을 판정한다 (백엔드 명세 §2.1).
-- email 은 초대 대상을 지정하는 유일한 열쇠라 계정마다 하나여야 한다 (유니크).
-- 대신 NULL 을 허용한다 — 이메일 제공 동의를 받지 못한 계정을 빈 문자열로 채우면
-- 그런 계정이 둘째로 생기는 순간 유니크 제약에 걸려 로그인 자체가 실패한다. NULL 끼리는 충돌하지 않는다.
CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider          VARCHAR(255)                NOT NULL,
    provider_id       VARCHAR(255)                NOT NULL,
    email             VARCHAR(255),
    name              VARCHAR(255)                NOT NULL,
    profile_image_url VARCHAR(255),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_provider UNIQUE (provider, provider_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- 태그 (기록에 다중 부착되는 자유 키워드)
CREATE TABLE IF NOT EXISTS tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tags_name UNIQUE (name)
);

-- 공유 그룹 (조회 전용 대상 목록)
-- group 은 SQL 예약어라 테이블명만 share_group 으로 둔다.
CREATE TABLE IF NOT EXISTS share_group
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id   BIGINT                      NOT NULL,
    name       VARCHAR(30)                 NOT NULL,
    memo       VARCHAR(200),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_share_group_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

-- 그룹 멤버 (소유자도 멤버 행을 가진다)
-- 정원(5명) 제한은 애플리케이션에서 검증한다. 행 수를 세는 조건이라 CHECK 로 표현할 수 없다.
CREATE TABLE IF NOT EXISTS group_member
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id  BIGINT                      NOT NULL,
    user_id   BIGINT                      NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_group_member UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_member_group FOREIGN KEY (group_id) REFERENCES share_group (id),
    CONSTRAINT fk_group_member_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 그룹 초대 (소유자가 특정 가입자 앞으로 보내는 요청. 받은 사람의 계정에 쌓인다)
-- 토큰·만료 컬럼을 두지 않는다. 초대가 서비스 밖으로 나가지 않아 추측할 대상도 수명도 없다.
-- 상태 컬럼도 두지 않는다. 수락·거절·철회가 모두 행 삭제로 끝난다.
-- 정원(5명) 판정은 수락 시점에만 하므로 대기 초대 건수는 제약하지 않는다.
CREATE TABLE IF NOT EXISTS group_invite
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id   BIGINT                      NOT NULL,
    invitee_id BIGINT                      NOT NULL,
    invited_by BIGINT                      NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_group_invite UNIQUE (group_id, invitee_id),
    CONSTRAINT fk_group_invite_group FOREIGN KEY (group_id) REFERENCES share_group (id),
    CONSTRAINT fk_group_invite_invitee FOREIGN KEY (invitee_id) REFERENCES users (id),
    CONSTRAINT fk_group_invite_inviter FOREIGN KEY (invited_by) REFERENCES users (id)
);

-- 끝난 초대의 기록 (공통 명세 §3.7). 대기 초대와 달리 지우지 않는다.
-- group_id 에 외래키를 걸지 않는다. 그룹이 지워져도 이력은 남아야 하는데, 외래키를 걸면
-- 이력까지 함께 지워지거나 그룹 삭제 자체가 막힌다. 대신 group_name 스냅샷으로 답한다.
-- unique 제약도 두지 않는다. 같은 상대에게 다시 초대해 다시 끝나면 항목이 하나 더 쌓인다.
CREATE TABLE IF NOT EXISTS invite_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id    BIGINT                      NOT NULL,
    group_name  VARCHAR(30)                 NOT NULL,
    invitee_id  BIGINT                      NOT NULL,
    invited_by  BIGINT                      NOT NULL,
    outcome     VARCHAR(20)                 NOT NULL,
    invited_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_invite_history_invitee FOREIGN KEY (invitee_id) REFERENCES users (id),
    CONSTRAINT fk_invite_history_inviter FOREIGN KEY (invited_by) REFERENCES users (id)
);

-- 여행 (기록의 상위 그룹이자 공유의 단위)
-- 공개 범위 컬럼은 이 테이블에만 존재한다. 기록은 범위를 갖지 않고 소속 여행의 값을 따른다.
-- visibility 기본값은 PRIVATE 이다. 값을 빠뜨린 INSERT 가 공개로 저장되는 쪽이
-- 훨씬 위험하므로 DB 기본값도 같은 방향으로 맞춰 둔다.
--
-- cover_photo_id 에는 외래키를 걸지 않는다. photos 가 trip_records 를, trip_records 가 trips 를
-- 참조해 순환이 생기는데, 이 스크립트는 인라인 FK 만 쓰고 PostgreSQL 의 ALTER TABLE ADD CONSTRAINT
-- 에는 IF NOT EXISTS 가 없어 재기동 시 실패한다. 사진 삭제 시의 커버 해제는 애플리케이션이 한다.
CREATE TABLE IF NOT EXISTS trips
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id       BIGINT                      NOT NULL,
    name           VARCHAR(50)                 NOT NULL,
    start_date     DATE                        NOT NULL,
    end_date       DATE                        NOT NULL,
    headcount      INTEGER                     NOT NULL,
    budget         BIGINT,
    memo           VARCHAR(1000),
    cover_photo_id BIGINT,
    visibility     VARCHAR(255)                NOT NULL DEFAULT 'PRIVATE',
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at     TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT ck_trips_visibility CHECK (visibility IN ('PRIVATE', 'GROUP', 'PUBLIC')),
    CONSTRAINT ck_trips_period CHECK (end_date >= start_date),
    CONSTRAINT ck_trips_headcount CHECK (headcount >= 1),
    CONSTRAINT ck_trips_budget CHECK (budget IS NULL OR budget >= 0),
    CONSTRAINT fk_trips_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

-- 여행 ↔ 그룹 공유 관계 (visibility = GROUP 일 때만 사용)
CREATE TABLE IF NOT EXISTS trip_shares
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trip_id  BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_trip_shares UNIQUE (trip_id, group_id),
    CONSTRAINT fk_trip_shares_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_trip_shares_group FOREIGN KEY (group_id) REFERENCES share_group (id)
);

-- 여행 기록 (반드시 여행 하나에 속한다)
-- author_id 와 visibility 컬럼을 두지 않는다. 둘 다 trips 에서 파생되며, 같은 사실을 두 곳에
-- 적으면 어긋나는 순간 어느 쪽이 맞는지 알 수 없다. 조회 권한 판정은 trip_id 로 조인해서 한다.
-- rating 은 0.5 ~ 5.0 을 0.5 단위로만 받는다. 허용 값을 CHECK 로 나열해 두면
-- 애플리케이션 검증이 우회되더라도 DB 가 마지막으로 막아 준다.
CREATE TABLE IF NOT EXISTS trip_records
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trip_id       BIGINT                      NOT NULL,
    name          VARCHAR(255)                NOT NULL,
    category      VARCHAR(255)                NOT NULL,
    address       VARCHAR(255)                NOT NULL,
    road_address  VARCHAR(255),
    external_link VARCHAR(255),
    latitude      DOUBLE PRECISION            NOT NULL,
    longitude     DOUBLE PRECISION            NOT NULL,
    rating        DOUBLE PRECISION            NOT NULL,
    memo          VARCHAR(1000),
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT ck_trip_records_category CHECK (category IN ('SIGHT', 'SHOPPING', 'FOOD')),
    CONSTRAINT ck_trip_records_rating CHECK (rating IN (0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5)),
    CONSTRAINT fk_trip_records_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

-- 기록 ↔ 태그 조인 테이블
CREATE TABLE IF NOT EXISTS trip_record_tags
(
    record_id BIGINT NOT NULL,
    tag_id    BIGINT NOT NULL,
    PRIMARY KEY (record_id, tag_id),
    CONSTRAINT fk_trip_record_tags_record FOREIGN KEY (record_id) REFERENCES trip_records (id),
    CONSTRAINT fk_trip_record_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);

-- 사진 (파일 본체는 app.storage 설정 위치에 저장하고 여기에는 메타데이터만 둔다)
-- 업로더 컬럼은 두지 않는다. 올릴 수 있는 사람이 소속 여행의 소유자뿐이라 trips.owner_id 와 같은 값이다.
CREATE TABLE IF NOT EXISTS photos
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id          BIGINT                      NOT NULL,
    storage_key        VARCHAR(255)                NOT NULL,
    original_file_name VARCHAR(255)                NOT NULL,
    content_type       VARCHAR(255)                NOT NULL,
    file_size_bytes    BIGINT                      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_photos_record FOREIGN KEY (record_id) REFERENCES trip_records (id)
);

-- 인덱스
-- PostgreSQL 은 외래키에 인덱스를 자동 생성하지 않으므로, 조회·삭제 시 사용되는 FK 컬럼에 직접 만든다.
-- soft delete 대상 테이블은 조회 시 deleted_at 조건이 항상 붙으므로 복합 인덱스로 만든다.
-- (PostgreSQL 의 부분 인덱스가 더 좋지만 H2 가 지원하지 않아 local 과 스크립트를 공유하지 못한다.)
CREATE INDEX IF NOT EXISTS idx_trip_records_trip ON trip_records (trip_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_trip_records_category ON trip_records (category);
CREATE INDEX IF NOT EXISTS idx_trip_records_created_at ON trip_records (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trip_record_tags_tag ON trip_record_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_group_member_user ON group_member (user_id);
-- 받은 초대 목록 조회 경로. (group_id 는 uk_group_invite 의 선두 컬럼이라 따로 만들지 않는다.)
CREATE INDEX IF NOT EXISTS idx_group_invite_invitee ON group_invite (invitee_id);
-- 보낸 대기 초대는 그룹을 가로질러 조회한다. 이 인덱스가 없으면 풀스캔이 된다 (명세 §4.8).
CREATE INDEX IF NOT EXISTS idx_group_invite_inviter ON group_invite (invited_by);
-- 이력은 양쪽 관점으로만 읽고, 언제나 끝난 시각 역순이다.
CREATE INDEX IF NOT EXISTS idx_invite_history_invitee ON invite_history (invitee_id, resolved_at DESC);
CREATE INDEX IF NOT EXISTS idx_invite_history_inviter ON invite_history (invited_by, resolved_at DESC);
CREATE INDEX IF NOT EXISTS idx_share_group_owner ON share_group (owner_id);
CREATE INDEX IF NOT EXISTS idx_photos_record ON photos (record_id);
-- 여행 목록은 범위(내 여행/공유받은/둘러보기)로 먼저 좁히고 생성일 또는 시작일로 정렬한다.
CREATE INDEX IF NOT EXISTS idx_trips_owner ON trips (owner_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_trips_visibility ON trips (visibility, deleted_at);
CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trips_start_date ON trips (start_date DESC);
CREATE INDEX IF NOT EXISTS idx_trip_shares_group ON trip_shares (group_id);
